# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-02 18:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plantid', models.CharField(max_length=250)),
                ('longitude', models.CharField(max_length=250)),
                ('latitude', models.CharField(max_length=250)),
                ('automode', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Sensors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tem_value', models.CharField(max_length=250)),
                ('hum_value', models.CharField(max_length=250)),
                ('soil_mois', models.CharField(max_length=250)),
                ('wat_lvl', models.CharField(max_length=250)),
                ('time', models.CharField(max_length=250)),
                ('rain', models.CharField(max_length=10)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plant.Plant')),
            ],
        ),
    ]
