# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-21 19:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='motorstate',
            field=models.CharField(default='False', max_length=200),
        ),
        migrations.AlterField(
            model_name='plant',
            name='automode',
            field=models.CharField(default='False', max_length=200),
        ),
    ]
